Solomon-T/instock

frontend/package-lock.json, frontend/package.json, frontend/src/App.test.js, frontend/src/actions/report_actions.js, frontend/src/components/app.jsx, frontend/src/reducers/reports_reducer.js, frontend/src/reducers/root_reducer.js, frontend/src/reducers/session_reducer.js, frontend/src/util/report_api_util.js, package-lock.json, package.json
=> Frontend 2

config/keys_dev.js, frontend/src/google_keys_dev.js
Resolves security issue by removing keys. Will remove from commit history as well.
=> Removes keys

frontend/public/index.html
The Google Maps Api was being referenced twice. Needed to remove line from html.index.
=> Removes duplicate script in html.index

frontend/src/components/map/map_container.js
mapped in fetch reports, fetch place reports, fetch report and compose report, connected to map presentational component
=> add map container

frontend/src/components/map/map.js
What it says on the can. Just adds some playful placeholder text on search bar.
=> Fix placeholder text on search bar

frontend/src/App.css, frontend/src/actions/report_actions.js, frontend/src/components/map/map.js, frontend/src/components/navbar/navbar.jsx, frontend/src/components/navbar/navbar_container.jsx, frontend/src/reducers/reports_reducer.js
+ Style changes include rounded off borders on containers including the address search bar
+ New welcome message includes changes to the mapStateToProps of the navbar_container
+ navbar now has access to a `currentUser` prop
=> Adds styling for borders, welcome message for logged in user

frontend/src/App.css, frontend/src/components/session/login_form.jsx, frontend/src/components/session/login_form_container.jsx, frontend/src/components/session/signup_form.jsx, frontend/src/components/session/signup_form_container.jsx
widened input fields on auth forms, added padding, style submit buttons and buttons taking user to other form
=> style login and signup forms, fix icon image paths

frontend/src/components/map/map.js, frontend/src/components/map/map_container.js, frontend/src/components/map/report_form.jsx, frontend/src/components/map/report_form_container.js, models/Report.js, routes/api/reports.js
* Model, Route, and form for the report is fixed so that the current user is assigned to a new report
* Fixed bug to ensure that only logged-in user can create a new report
=> Assigns currentUser to new Report

frontend/src/App.css, frontend/src/components/map/map.js, frontend/src/components/map/report_form.jsx
Last commit included stray debuggers. These were removed.
Additionally, styling was added for the report infoWindow and the report form now has placeholder text.
=> Removes debuggers, adds styling to report infoWindow

frontend/src/App.css, frontend/src/components/navbar/navbar.jsx, frontend/src/components/navbar/navbar_container.jsx, frontend/src/components/session/login_form.jsx, frontend/src/util/session_api_util.js
Adds demo-login button on the navbar. Includes some styling changes on the navbar and limits the default width for the navbar.
Hard codes a demo-user that is passed to the login function inside the navbar. Navbar gets the login function via MapStateToDispatch.
=> Adds demo-user login

frontend/src/actions/session_actions.js, frontend/src/components/session/login_form.jsx, frontend/src/reducers/session_errors_reducer.js
Ensures that when a user logs in with mismatched email-password combination they receive errors in the front end
Started work on the same kind of errors for signup but waiting for changes coming from another branch
=> Fixes errors for invalid login credentials

app.js, frontend/src/actions/session_actions.js, frontend/src/components/map/map.js, frontend/src/components/navbar/navbar.jsx, frontend/src/components/session/signup_form.jsx, routes/api/approvals.js, routes/api/reports.js, routes/api/users.js
Nested login Axios call inside signup Axios call to log user in on backend whenever they sign up. Previously user was being logged in only on the frontend.
=> Fixed error where user logging in through sign up page was logged out on page refresh

frontend/app.js, frontend/src/App.css, frontend/src/components/navbar/navbar.css, frontend/src/components/navbar/navbar.jsx, frontend/src/components/session/signup_form.jsx
###Summary
Add responsive burger nav bar menu
###Technical Notes
-Made us of media queries @768px.
-Not sure why we could not use just one media query for when user is logged in and when user is not logged in. During testing, both media queries were necessary even after refactoring.
-Not sure why cursor: pointer and button:hover are not rendering with regard to CSS
=> Burger menu

app.js, frontend/app.js, frontend/src/actions/report_actions.js, frontend/src/components/map/map.js, frontend/src/components/map/map_container.js, frontend/src/components/map/report_form_container.js, frontend/src/components/session/signup_form.jsx, frontend/src/index.js, frontend/src/util/report_api_util.js, frontend/src/util/route_util.js, routes/api/reports.js, validation/reports.js
Added feature where users can approve reports by other users.
=> Adds ability for users to approve reports

frontend/src/App.css, frontend/src/actions/session_actions.js, frontend/src/components/session/login_form.jsx, frontend/src/components/session/login_form_container.jsx, frontend/src/components/session/signup_form.jsx, frontend/src/components/session/signup_form_container.jsx
When a user signs up with email that is already assigned to an existing user, they should receive an error message in the form.
In addition to the displaying frontend errors, also made a few small style changes to the form.
=> Ensures that signup errors are visible on the frontend

frontend/src/App.css, frontend/src/components/map/map.css, frontend/src/components/map/map.js, frontend/src/components/map/report.css, frontend/src/components/map/report_form.jsx, frontend/src/components/modal/modal.css, frontend/src/components/modal/modal.jsx, frontend/src/components/navbar/navbar.jsx, frontend/src/components/session/login_form.jsx, frontend/src/components/session/session_form.css, frontend/src/components/session/signup_form.jsx
The map automatically centered at my geolocation. While the map is centered on a different position, I should be able to return the center of the map to my geolocation using a button.
The geolocation function utilizes the browser's [native geolocation service](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition). The button is added to the map as a div as a [Google Maps custom control](https://developers.google.com/maps/documentation/javascript/controls).
=> Adds button to recenter relative to user's geolocation

frontend/src/components/map/map.css, frontend/src/components/map/map.js, frontend/src/components/map/report.css
+ adds ability for a user to see approvals count without opening up an individual report
+ sets up button to remove approval (need to add backend)
+ removes count from the `infoWindow`
+ `infoWindow` no longer automatically closes on approval update
Some of the report code has been encapsulated into a variable `reportInfoWindow`. The goal was to test the way that we might start to encapsulate report code into its own component. Next PR will be focused on completing that work.
=> Adds approval badges, reduces some flickering

frontend/src/components/footer/footer.css, frontend/src/components/navbar/navbar.css, frontend/src/components/navbar/navbar.jsx
Made a few adjustment to the flex container for the `nav-header` that helps to make sure that the Logo image stays centered vertically until the welcome message moves below it.
=> Small adjustment to flex container

frontend/src/components/help/help.jsx, frontend/src/components/help/help_container.js, frontend/src/components/modal/modal.jsx, frontend/src/components/navbar/navbar.jsx, frontend/src/components/session/session_form.css
Added the help button on nav-bar on both occasions when the user is logged in or not. I used the styling available but open to do any adjustments if required.
=> Help button and model added

frontend/public/index.html
Saved a screenshot to my imgur account, link here: https://i.imgur.com/WYxQqnL.png
=> Added meta tags to index.html to allow for social media posts to grab a screenshot of the app as the default image.

frontend/package-lock.json, frontend/package.json, frontend/src/App.test.js, frontend/src/components/navbar/navbar.jsx, frontend/src/components/navbar/navbar.test.js, frontend/test/testUtils.js
Adds [Enzyme](https://github.com/enzymejs/enzyme) test framework and several starter tests for the header component.
Enzyme is used on top of the Jest framework for an easier development experience. In the tests included here, Enzyme specifically helps us by providing the [Shallow Rendering API](https://enzymejs.github.io/enzyme/docs/api/shallow.html), which ensures that a unit test for a particular component will only test that component without accidentally testing the behavior of child components.
Enzyme is not dogmatic about the way that you organize tests. For now, I have included a test file in the same directory as the component being tested. Naming structure for test files should be `component.test.js`.
Elements that are being tested are referenced via a [custom html …
=> Adds enzme test framework and tests for the header component
